name: Generate historical view

# On the off-chance that we want to revert to a previous version so that things still work,
on:
  push:
    branches:
        - history

# Cacnel previous runs if a new push is sent
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  generate-historical-dashboard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      # Downloading both the repositories to simulate the original task
      - uses: actions/checkout@main
        with:
          path: 'parent/${{ github.event.repository.name }}'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'parent/${{ github.event.repository.name }}/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
